services:
  app:
    tty: true
    networks:
      - app_network
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # app:
  #   build:
  #     context: .
  #   container_name: rpg
  #   ports:
  #     - "3000:3000"
  #   tty: true
  #   volumes:
  #     - ./app:/app
  #     - node_modules:/app/node_modules
  #   working_dir: /app
  #   command: npm run dev
  #   depends_on:
  #     - db
networks:
  app_network:
    driver: bridge

volumes:
  db-data:
  node_modules:
